# ???? ?????? (H2 ??? ??????????)
spring:

  application:
    name: OnlineShop

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: update

# Email-???????????
  mail:
    host: smtp.example.com
    port: 587
    username: hello@google.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ????????? ?????? (????????)
payment:
  gateway: mock
  currency: USD
  min-amount: 10.00

# ??????
server:
  port: 8080


